//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguagePack {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanguagePack.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接受.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应收账款.
        /// </summary>
        public static string AccountReceivable {
            get {
                return ResourceManager.GetString("AccountReceivable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 应收日期.
        /// </summary>
        public static string AccountReceivableDate {
            get {
                return ResourceManager.GetString("AccountReceivableDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动作.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动作显示名称.
        /// </summary>
        public static string ActionDisplayName {
            get {
                return ResourceManager.GetString("ActionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 动作名称.
        /// </summary>
        public static string ActionName {
            get {
                return ResourceManager.GetString("ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动内容.
        /// </summary>
        public static string ActivityContent {
            get {
                return ResourceManager.GetString("ActivityContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 报名截止日期.
        /// </summary>
        public static string ActivityDeadline {
            get {
                return ResourceManager.GetString("ActivityDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动地点.
        /// </summary>
        public static string ActivitySite {
            get {
                return ResourceManager.GetString("ActivitySite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动开始时间.
        /// </summary>
        public static string ActivityStartDateTime {
            get {
                return ResourceManager.GetString("ActivityStartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 活动主题.
        /// </summary>
        public static string ActivityTitle {
            get {
                return ResourceManager.GetString("ActivityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 地址.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 金额.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 区域.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 区域显示名称.
        /// </summary>
        public static string AreaDisplayName {
            get {
                return ResourceManager.GetString("AreaDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 区域名称.
        /// </summary>
        public static string AreaName {
            get {
                return ResourceManager.GetString("AreaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 附件.
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 返回.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始时间.
        /// </summary>
        public static string BeginTime {
            get {
                return ResourceManager.GetString("BeginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 业务.
        /// </summary>
        public static string Business {
            get {
                return ResourceManager.GetString("Business", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 业务机会.
        /// </summary>
        public static string BusinessChance {
            get {
                return ResourceManager.GetString("BusinessChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 业务机会.
        /// </summary>
        public static string BusinessChanceName {
            get {
                return ResourceManager.GetString("BusinessChanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 业务名称.
        /// </summary>
        public static string BusinessName {
            get {
                return ResourceManager.GetString("BusinessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 业务状态.
        /// </summary>
        public static string BusinessState {
            get {
                return ResourceManager.GetString("BusinessState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 业务状态.
        /// </summary>
        public static string BusinessStateName {
            get {
                return ResourceManager.GetString("BusinessStateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日历.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 颜色.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 沟通结果.
        /// </summary>
        public static string CommunicateResult {
            get {
                return ResourceManager.GetString("CommunicateResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 沟通内容.
        /// </summary>
        public static string CommunicationContent {
            get {
                return ResourceManager.GetString("CommunicationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公司.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认密码.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联系人.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 联系人名称.
        /// </summary>
        public static string ContactName {
            get {
                return ResourceManager.GetString("ContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控制器显示名称.
        /// </summary>
        public static string ControllerDisplayName {
            get {
                return ResourceManager.GetString("ControllerDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 控制器名称.
        /// </summary>
        public static string ControllerName {
            get {
                return ResourceManager.GetString("ControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数量.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建日期.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建知识.
        /// </summary>
        public static string CreateKnowledge {
            get {
                return ResourceManager.GetString("CreateKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建计划.
        /// </summary>
        public static string CreatePlan {
            get {
                return ResourceManager.GetString("CreatePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新建项目.
        /// </summary>
        public static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户等级.
        /// </summary>
        public static string CustomerLevel {
            get {
                return ResourceManager.GetString("CustomerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户等级.
        /// </summary>
        public static string CustomerLevelName {
            get {
                return ResourceManager.GetString("CustomerLevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户名称.
        /// </summary>
        public static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户类型.
        /// </summary>
        public static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 客户类型.
        /// </summary>
        public static string CustomerTypeName {
            get {
                return ResourceManager.GetString("CustomerTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部门.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部门编码.
        /// </summary>
        public static string DepartmentCode {
            get {
                return ResourceManager.GetString("DepartmentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 部门名称.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 桌面.
        /// </summary>
        public static string Desktop {
            get {
                return ResourceManager.GetString("Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 查看.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 差额.
        /// </summary>
        public static string Difference {
            get {
                return ResourceManager.GetString("Difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 禁用.
        /// </summary>
        public static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 显示名称.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮箱.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 表情.
        /// </summary>
        public static string Emoticon {
            get {
                return ResourceManager.GetString("Emoticon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 启用.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束日期.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束时间.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 企业.
        /// </summary>
        public static string Enterprise {
            get {
                return ResourceManager.GetString("Enterprise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 企业名称.
        /// </summary>
        public static string EnterpriseName {
            get {
                return ResourceManager.GetString("EnterpriseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 企业简称.
        /// </summary>
        public static string EnterpriseShortName {
            get {
                return ResourceManager.GetString("EnterpriseShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 扩展.
        /// </summary>
        public static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 否.
        /// </summary>
        public static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 传真.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件地址.
        /// </summary>
        public static string FileUrl {
            get {
                return ResourceManager.GetString("FileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成时间.
        /// </summary>
        public static string FinishTime {
            get {
                return ResourceManager.GetString("FinishTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流程.
        /// </summary>
        public static string Flow {
            get {
                return ResourceManager.GetString("Flow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流程名称.
        /// </summary>
        public static string FlowName {
            get {
                return ResourceManager.GetString("FlowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 流程任务.
        /// </summary>
        public static string FlowTask {
            get {
                return ResourceManager.GetString("FlowTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全局.
        /// </summary>
        public static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google事件编号.
        /// </summary>
        public static string GoogleEventEntryId {
            get {
                return ResourceManager.GetString("GoogleEventEntryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google账户密码.
        /// </summary>
        public static string GooglePassword {
            get {
                return ResourceManager.GetString("GooglePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google账户.
        /// </summary>
        public static string GoogleUserName {
            get {
                return ResourceManager.GetString("GoogleUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 头像.
        /// </summary>
        public static string Head {
            get {
                return ResourceManager.GetString("Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主机.
        /// </summary>
        public static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图标.
        /// </summary>
        public static string Ico {
            get {
                return ResourceManager.GetString("Ico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编号.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已开发票.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发票类型.
        /// </summary>
        public static string InvoiceType {
            get {
                return ResourceManager.GetString("InvoiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关键词.
        /// </summary>
        public static string Keyword {
            get {
                return ResourceManager.GetString("Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 知识内容.
        /// </summary>
        public static string KnowledgeContent {
            get {
                return ResourceManager.GetString("KnowledgeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 知识标题.
        /// </summary>
        public static string KnowledgeTitle {
            get {
                return ResourceManager.GetString("KnowledgeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上级项目信息.
        /// </summary>
        public static string LastProjectInfo {
            get {
                return ResourceManager.GetString("LastProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 负责人.
        /// </summary>
        public static string Leader {
            get {
                return ResourceManager.GetString("Leader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登入.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 最大用户.
        /// </summary>
        public static string MaxUser {
            get {
                return ResourceManager.GetString("MaxUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 消息.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 里程碑.
        /// </summary>
        public static string Milestone {
            get {
                return ResourceManager.GetString("Milestone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 移动电话.
        /// </summary>
        public static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 模块.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 月.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新密码.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 旧密码.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实收账款.
        /// </summary>
        public static string PaidIn {
            get {
                return ResourceManager.GetString("PaidIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 实收日期.
        /// </summary>
        public static string PaidInDate {
            get {
                return ResourceManager.GetString("PaidInDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 参数.
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 密码.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 周期.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 图片.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计划.
        /// </summary>
        public static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计划主题.
        /// </summary>
        public static string PlanTitle {
            get {
                return ResourceManager.GetString("PlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 计划类型.
        /// </summary>
        public static string PlanType {
            get {
                return ResourceManager.GetString("PlanType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 人数.
        /// </summary>
        public static string Population {
            get {
                return ResourceManager.GetString("Population", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 职务.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 邮编.
        /// </summary>
        public static string Postcode {
            get {
                return ResourceManager.GetString("Postcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目信息.
        /// </summary>
        public static string ProjectInfo {
            get {
                return ResourceManager.GetString("ProjectInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目信息.
        /// </summary>
        public static string ProjectInfoId {
            get {
                return ResourceManager.GetString("ProjectInfoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目状态.
        /// </summary>
        public static string ProjectInfoState {
            get {
                return ResourceManager.GetString("ProjectInfoState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目状态.
        /// </summary>
        public static string ProjectInfoStateName {
            get {
                return ResourceManager.GetString("ProjectInfoStateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目名称.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目目标.
        /// </summary>
        public static string ProjectObjective {
            get {
                return ResourceManager.GetString("ProjectObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目标签.
        /// </summary>
        public static string ProjectTag {
            get {
                return ResourceManager.GetString("ProjectTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目任务.
        /// </summary>
        public static string ProjectTask {
            get {
                return ResourceManager.GetString("ProjectTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目任务名称.
        /// </summary>
        public static string ProjectTaskName {
            get {
                return ResourceManager.GetString("ProjectTaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目任务说明.
        /// </summary>
        public static string ProjectTaskObjective {
            get {
                return ResourceManager.GetString("ProjectTaskObjective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 项目成员.
        /// </summary>
        public static string ProjectUsers {
            get {
                return ResourceManager.GetString("ProjectUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 公开.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 等级.
        /// </summary>
        public static string Raty {
            get {
                return ResourceManager.GetString("Raty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记录编号.
        /// </summary>
        public static string RecordId {
            get {
                return ResourceManager.GetString("RecordId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 注册.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备注.
        /// </summary>
        public static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 记住.
        /// </summary>
        public static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提醒时间.
        /// </summary>
        public static string RemindTime {
            get {
                return ResourceManager.GetString("RemindTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重复新密码.
        /// </summary>
        public static string ReNewPassword {
            get {
                return ResourceManager.GetString("ReNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 回复.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 角色名.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 搜索.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 排序.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始日期.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始时间.
        /// </summary>
        public static string StarTime {
            get {
                return ResourceManager.GetString("StarTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始搜索.
        /// </summary>
        public static string StartSearch {
            get {
                return ResourceManager.GetString("StartSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始时间.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 统计.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统区域.
        /// </summary>
        public static string SysArea {
            get {
                return ResourceManager.GetString("SysArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 系统编号.
        /// </summary>
        public static string SystemId {
            get {
                return ResourceManager.GetString("SystemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标签.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新窗口.
        /// </summary>
        public static string TargetBlank {
            get {
                return ResourceManager.GetString("TargetBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 电话.
        /// </summary>
        public static string Telephony {
            get {
                return ResourceManager.GetString("Telephony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主题.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 今天.
        /// </summary>
        public static string ToDay {
            get {
                return ResourceManager.GetString("ToDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是.
        /// </summary>
        public static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 更新日期.
        /// </summary>
        public static string UpdatedDate {
            get {
                return ResourceManager.GetString("UpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 网址.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户中心.
        /// </summary>
        public static string UserCenter {
            get {
                return ResourceManager.GetString("UserCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名被禁用.
        /// </summary>
        public static string UserDisabled {
            get {
                return ResourceManager.GetString("UserDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 用户名密码错误.
        /// </summary>
        public static string UserNamePasswordError {
            get {
                return ResourceManager.GetString("UserNamePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 有效期.
        /// </summary>
        public static string Validity {
            get {
                return ResourceManager.GetString("Validity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 周.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作流名称.
        /// </summary>
        public static string WorkFlowName {
            get {
                return ResourceManager.GetString("WorkFlowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工作流步骤名称.
        /// </summary>
        public static string WorkFlowStepName {
            get {
                return ResourceManager.GetString("WorkFlowStepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 年.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
